import 'package:flutter/material.dart';

List<String> items = [
  'Alphabets',
  'Fruits',
  'Vegetables',
  'Body',
  'Birds',
  'Animals',
];

List<Color> colorItem = [
  Colors.amber,
  Colors.amberAccent,
  Colors.blue,
  Colors.blueAccent,
  Colors.blueGrey,
  Colors.brown,
  Colors.cyan,
  Colors.cyanAccent,
  Colors.deepOrange,
  Colors.deepOrangeAccent,
  Colors.deepPurple,
  Colors.deepPurpleAccent,
  Colors.green,
  Colors.greenAccent,
  Colors.grey,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.lightBlue,
  Colors.lightBlueAccent,
  Colors.lightGreen,
  Colors.lightGreenAccent,
  Colors.lime,
  Colors.limeAccent,
  Colors.orange,
  Colors.orangeAccent,
  Colors.pink,
  Colors.pinkAccent,
  Colors.purple,
  Colors.purpleAccent,
  Colors.red,
  Colors.redAccent,
  Colors.teal,
  Colors.tealAccent,
  Colors.yellow,
  Colors.yellowAccent,
];

List<List<String>> lists = [
  [
    'A for Apple ',
    'B for Ball ',
    'C for Cat ',
    'D for Dog ',
    'E for Elephant',
    'F for Fish ',
    'G for Gun ',
    'H for Hen ',
    'I for Ice-Cream ',
    'J for Jug ',
    'K for Kite ',
    'L for Lion ',
    'M for Mug ',
    'N for Nest ',
    'O for Orange ',
    'P for Parrot ',
    'Q for Queen ',
    'R for Rat ',
    'S for Ship ',
    'T for Tank ',
    'U for Umbrella ',
    'V for Van ',
    'W for Wall ',
    'X for Xray ',
    'Y for Yaak ',
    'Z for Zebra ',
  ],
  [
    'Apple',
    'Mango',
    'Banana',
    'Grapes',
    'Orange',
    'Strawberry',
    'Litchi',
  ],
  [
    'Potato',
    'Onion',
    'Cucumber',
    'Lady Finger',
    'Carrot',
    'Garlic',
    'Ginger',
    'Chilli',
  ],
  [
    'Head',
    'Nose',
    'Eyes',
    'Hand',
    'Ears',
    'Leg',
    'Chest',
    'Neck',
    'Fingers',
    'Arm',
  ],
  [
    'Parrot',
    'Pigeon',
    'Peacock',
    'Crow',
    'Nightingale',
    'Sparrow',
    'Eagle',
    'Kite',
  ],
  [
    'Ant',
    'Cat',
    'Dog',
    'Elephant',
    'Fish',
    'Goat',
    'Hen',
    'Jaguar',
    'Lion',
    'Monkey',
    'Tiger',
  ],
];
